[build]
  command = "npm run build && npm run build:lambda"
  functions = "functions"
  publish = "build"

[dev]
  command = "npm start"
  port = 3000
  functionsPort = 34567
  targetPort = 3000
  publish = "dist"


[[headers]]
  for = "/*"

  [headers.values]
    Access-Control-Allow-Headers = "*"